-- MySQL Script generated by MySQL Workbench
-- Tue Dec 21 19:35:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paciente` (
  `cui` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT 'Ciudad',
  `fecha_nacimiento` DATE NOT NULL,
  `nit` VARCHAR(8) NULL DEFAULT 'C/F',
  `telefono` CHAR(8) NOT NULL,
  PRIMARY KEY (`cui`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `user` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `tipo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_examen` (
  `idtipo_examen` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`idtipo_examen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medicos` (
  `id_medicos` INT NOT NULL,
  `nombre_medico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_medicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orden` (
  `num_orden` INT NOT NULL AUTO_INCREMENT,
  `total` DOUBLE NOT NULL,
  `fecha_consulta` DATE NOT NULL,
  `paciente_cui` INT NOT NULL,
  `usuario_user` VARCHAR(20) NOT NULL,
  `estado` TINYINT(1) NULL DEFAULT 0,
  `medicos_id_medicos` INT NOT NULL,
  PRIMARY KEY (`num_orden`),
  INDEX `fk_orden_paciente1_idx` (`paciente_cui` ASC) VISIBLE,
  INDEX `fk_orden_usuario1_idx` (`usuario_user` ASC) VISIBLE,
  INDEX `fk_orden_medicos1_idx` (`medicos_id_medicos` ASC) VISIBLE,
  CONSTRAINT `fk_orden_paciente1`
    FOREIGN KEY (`paciente_cui`)
    REFERENCES `mydb`.`paciente` (`cui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_usuario1`
    FOREIGN KEY (`usuario_user`)
    REFERENCES `mydb`.`usuario` (`user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_medicos1`
    FOREIGN KEY (`medicos_id_medicos`)
    REFERENCES `mydb`.`medicos` (`id_medicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_orden` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detalle_ordencol` VARCHAR(45) NULL,
  `orden_num_orden` INT NOT NULL,
  `tipo_examen_idtipo_examen` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_orden_orden1_idx` (`orden_num_orden` ASC) VISIBLE,
  INDEX `fk_detalle_orden_tipo_examen1_idx` (`tipo_examen_idtipo_examen` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_orden_orden1`
    FOREIGN KEY (`orden_num_orden`)
    REFERENCES `mydb`.`orden` (`num_orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_orden_tipo_examen1`
    FOREIGN KEY (`tipo_examen_idtipo_examen`)
    REFERENCES `mydb`.`tipo_examen` (`idtipo_examen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resultados` (
  `idelemento_examinar` INT NOT NULL AUTO_INCREMENT,
  `nombre_elemento` VARCHAR(45) NOT NULL,
  `resultado` DOUBLE NULL,
  `unidades` VARCHAR(45) NULL,
  `rango_referencia_inferior` DOUBLE NULL,
  `rango_referencia_superior` DOUBLE NULL,
  `comentario` VARCHAR(300) NULL,
  `detalle_orden_id` INT NOT NULL,
  PRIMARY KEY (`idelemento_examinar`),
  INDEX `fk_resultados_detalle_orden1_idx` (`detalle_orden_id` ASC) VISIBLE,
  CONSTRAINT `fk_resultados_detalle_orden1`
    FOREIGN KEY (`detalle_orden_id`)
    REFERENCES `mydb`.`detalle_orden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`elementos_examen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`elementos_examen` (
  `id_tipo_subexamen` INT NOT NULL,
  `tipo_subexamen` VARCHAR(45) NOT NULL,
  `tipo_examen_idtipo_examen` INT NOT NULL,
  PRIMARY KEY (`id_tipo_subexamen`),
  INDEX `fk_elementos_examen_tipo_examen1_idx` (`tipo_examen_idtipo_examen` ASC) VISIBLE,
  CONSTRAINT `fk_elementos_examen_tipo_examen1`
    FOREIGN KEY (`tipo_examen_idtipo_examen`)
    REFERENCES `mydb`.`tipo_examen` (`idtipo_examen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
